const boats = [
  {
    type: "sailboat",
    images: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
    ],
    pricing: {},
    requiresLicense: true,
    capacity: 8,
    requiresShipmaster: true,
    year: null,
    horsePower: 55,
    id: "bavaria-39",
    name: "Bavaria 39",
    description: "Descripción Breve",
    text: "Texto Decorativo",
  },
  {
    type: "sailboat",
    images: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
    ],
    pricing: {},
    requiresLicense: true,
    capacity: 8,
    requiresShipmaster: true,
    year: null,
    horsePower: 42,
    id: "maryola-aquadrac-35",
    name: "Maryola Aquadrac 35",
    description: "Descripción Breve",
    text: "Texto Decorativo",
  },
  {
    type: "yatch",
    images: ["1", "2", "3", "4"],
    pricing: {},
    requiresLicense: true,
    capacity: 6,
    requiresShipmaster: false,
    year: 2019,
    horsePower: 60,
    id: "saver-585",
    name: "Saver 585",
    description: "Descripción Breve",
    text: "Texto Decorativo",
  },
  {
    type: "yatch",
    images: [],
    pricing: {},
    requiresLicense: true,
    capacity: 8,
    requiresShipmaster: false,
    year: 2022,
    horsePower: 80,
    id: "mareti-600",
    name: "Mareti 600",
    description: "Descripción Breve",
    text: "Texto Decorativo",
  },
  {
    type: "yatch",
    images: ["1", "2", "3"],
    pricing: {},
    requiresLicense: false,
    capacity: null,
    requiresShipmaster: false,
    year: 2021,
    horsePower: 15,
    id: "mareti-500",
    name: "Mareti 500 Classic",
    description: "Descripción Breve",
    text: "Texto Decorativo",
  },
  {
    type: "yatch",
    images: ["1", "2"],
    pricing: {},
    requiresLicense: false,
    capacity: null,
    requiresShipmaster: false,
    year: 2022,
    horsePower: 15,
    id: "karnic-400",
    name: "Karnic 400",
    description: "Descripción Breve",
    text: "Texto Decorativo",
  },
];

export default boats;
/* 
export const genereateNumArray = (rep, str = false) => {
  const arr = [];
  for (let i = 1; i <= rep; i++) {
    arr.push(i);
  }
  if (str) {
    return arr.map((v) => `${v}`);
  } else {
    return arr;
  }
}; */
